apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /chroot/flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-path-traversal-secret-provider
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - two
            - weight: 50
              preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - one
            - weight: 75
              preference:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - three
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:69966c59a76cb2a01f390c74a10978271b4e54b600da2bbcb3f502dba64a4a91
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:fd53a6ebc89c9c9341b9ec933f7beb9108c663604865b3b5b2a26dfc41d5efb3
