apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-gitlab-cve-2021-22205
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:0bfa6c80d9dfc3e6c8ad1e2e72fd6df0af7fc7a9634ff48e946f6b396f844d16
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:7734807a84c4d31f528ca32a71ddf50d738a286172f696ba3bf7c8ab89ad2fe1
